# Generated by Django 2.0.7 on 2018-07-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_note_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='public',
            new_name='is_public',
        ),
    ]
