# Generated by Django 2.0.7 on 2018-07-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180721_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_public',
            field=models.CharField(choices=[('ALL', 1), ('FRND', 2), ('GROUP', 3)], default='FRND', max_length=5),
        ),
    ]
