# Generated by Django 2.0.7 on 2018-07-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180721_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_public',
        ),
        migrations.AddField(
            model_name='note',
            name='privacy',
            field=models.CharField(choices=[('PRIVT', 1), ('FRND', 2), ('ALL', 3), ('GROUP', 4)], default='PRIVT', max_length=5),
        ),
    ]
