# Generated by Django 2.0.7 on 2018-07-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180721_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='privacy',
            field=models.CharField(choices=[('PRIVATE', 1), ('FRIEND', 2), ('ALL', 3), ('GROUP', 4)], default='PRIVATE', max_length=7),
        ),
    ]
