# Generated by Django 2.0.7 on 2018-07-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180721_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='privacy',
            field=models.CharField(choices=[('PRIVATE', 1), ('FRIEND', 2), ('PUBLIC', 3), ('GROUP', 4)], default='PRIVATE', max_length=7),
        ),
    ]
