# Generated by Django 2.0.7 on 2018-07-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180724_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
